### ISSUE TITLE
Your GitHub Page Failure

### ISSUE THREAD

**Issue by stewartweiss** [hunter-college-ossd-fall-2019/sophiabonsu-weekly#1]
Your GitHub pages are not building because when you edited the about.md file, you removed critical lines. From this:
```
---
layout: page
title: About
permalink: /about/
---
```
To this:
```
---
Sophia's Blog #: 1
title: About Me
permalink: /about/
---
```
This page is the About page, not a blog post. Revert those lines to their original form and then it will work.

**Comment by sophiabonsu** [comment]
Fixed it ! Thank you so  much!
